[package]
name = "rewrk"
version = "0.3.0"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>", "Programatik <programatik29@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.9.0", features = ["rt", "rt-multi-thread", "net", "macros"] }
hyper = { version = "0.14.11", features = ["runtime", "client", "http1", "http2"] }
tower = { version = "0.4.7", features = ["util"] }
rustls = "0.19.1"
tokio-rustls = "0.22.0"
rustls-native-certs = "0.5.0"
clap = "2.33.3"
colored = "2"
regex = "1.4.*"
rand = "0.8.3"
serde_json = "1"
http = "0.2.4"
anyhow = "1"
